name : Test document with sphinx

#exeuction of workflow

on:
   push:
      branches: [ main ]

jobs:

   build_doc_with_sphinx:
      run-on: ubuntu-latest
      env:
         GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      steps:
         - name: checkout the repo
           uses: actions/checkout@v3
        
